spring:
  application:
    name: api-test
  profiles:
    include: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true

server:
  servlet:
    context-path: /api
  port: 8080

logging:
  level:
    com:
      sk:
        skala:
          axcalibur:
            apitest: info

