spring:
  application:
    name: spec
  config:
    import: "optional:file:.env"
  profiles:
    include: dev
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    url: {MARIADB_URL}
    username: {MARIADB_USERNAME}
    password: {MARIADB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        default_schema: {MARIADB_DEFAULT_SCHEMA}
#  data:
#    redis:
#      host: {REDIS_HOST}
#      port: {REDIS_PORT}
#      password: {REDIS_PASSWORD}


server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com:
      sk:
        skala:
          axcalibur: DEBUG












